# Generated by Django 5.0.14 on 2026-06-24 20:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.CharField(max_length=100)),
                ("details", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_auditlog",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DataRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("row_index", models.IntegerField()),
                ("data", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In Stock", "In Stock"),
                            ("Out of Stock", "Out of Stock"),
                        ],
                        default="In Stock",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=120)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_datarow",
                "ordering": ["-modified_at"],
            },
        ),
    ]
