# Generated by Django 5.0.14 on 2026-06-24 20:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_row_id", models.IntegerField()),
                ("data", models.JSONField()),
                ("deleted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("restored", models.BooleanField(default=False)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Trash",
                "db_table": "trash_trash",
                "ordering": ["-deleted_at"],
            },
        ),
    ]
